provider = "bunny"
remote_path = ""
local_path = "dist"
ignore = []
remote_ignore = []

[bunny]
storage_zone = "zydro-documentation"
custom_404_page = "/index.html"

[[redirects]]
    from = "*://zydro-documentation.b-cdn.net/*"
    to = "https://docs.zydromarine.com{{path}}"
